package com.pako2k.banknotescatalog.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00696A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFa0dcdc)
val md_theme_light_onPrimaryContainer = Color(0xFF002020)
val md_theme_light_secondary = Color(0xFF006A6A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF6FF7F7)
val md_theme_light_onSecondaryContainer = Color(0xFF002020)
val md_theme_light_tertiary = Color(0xFF006D3B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF89F9AE)
val md_theme_light_onTertiaryContainer = Color(0xFF00210E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF3FFFA)
val md_theme_light_onBackground = Color(0xFF00201A)
val md_theme_light_surface = Color(0xFFF3FFFA)
val md_theme_light_onSurface = Color(0xFF00201A)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E4)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4948)
val md_theme_light_outline = Color(0xFF6F7979)
val md_theme_light_inverseOnSurface = Color(0xFFB7FFEC)
val md_theme_light_inverseSurface = Color(0xFF00382E)
val md_theme_light_inversePrimary = Color(0xFF4CDADB)
val md_theme_light_shadow = Color(0xFF999999)
val md_theme_light_surfaceTint = Color(0xFF00696A)
val md_theme_light_outlineVariant = Color(0xFFBEC8C8)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF4CDADB)
val md_theme_dark_onPrimary = Color(0xFF003737)
val md_theme_dark_primaryContainer = Color(0xFF004F50)
val md_theme_dark_onPrimaryContainer = Color(0xFF6FF6F8)
val md_theme_dark_secondary = Color(0xFF4CDADA)
val md_theme_dark_onSecondary = Color(0xFF003737)
val md_theme_dark_secondaryContainer = Color(0xFF004F50)
val md_theme_dark_onSecondaryContainer = Color(0xFF6FF7F7)
val md_theme_dark_tertiary = Color(0xFF6DDC94)
val md_theme_dark_onTertiary = Color(0xFF00391C)
val md_theme_dark_tertiaryContainer = Color(0xFF00522B)
val md_theme_dark_onTertiaryContainer = Color(0xFF89F9AE)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF00201A)
val md_theme_dark_onBackground = Color(0xFF79F8DC)
val md_theme_dark_surface = Color(0xFF00201A)
val md_theme_dark_onSurface = Color(0xFF79F8DC)
val md_theme_dark_surfaceVariant = Color(0xFF3F4948)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC8C8)
val md_theme_dark_outline = Color(0xFF889392)
val md_theme_dark_inverseOnSurface = Color(0xFF00201A)
val md_theme_dark_inverseSurface = Color(0xFF79F8DC)
val md_theme_dark_inversePrimary = Color(0xFF00696A)
//val md_theme_dark_shadow = Color(0xFF333333)
val md_theme_dark_surfaceTint = Color(0xFF4CDADB)
val md_theme_dark_outlineVariant = Color(0xFF3F4948)
val md_theme_dark_scrim = Color(0xFF000000)

val color_table_header_top = Color(0xFF6E3737)
val color_table_header_bottom = Color(0xFF964141)
val color_table_header_text = Color(0xFFFFFFFF)

val color_table_row_odd = Color(0xFFF0F4F4)
val color_table_row_even = Color(0xFFF7FBFB)

val color_table_link_prim = Color(0xFF00391C)
val color_table_link_sec = Color(0xFF00696A)

val background_color_territory_badge = Color(0xFFF7F8F8)
val color_territory_badge = Color(0xFF00696A)

val color_is_favourite = Color(0xFFFFD700)